language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - GH_REF: github.com/Rebilly/ReDoc.git
    - GIT_AUTHOR_EMAIL: redoc-bot@users.noreply.github.com
    - GIT_AUTHOR_NAME: RedocBot
script: npm run bundle
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.bash
  on:
    branch: master
