language: node_js
node_js:
  - "10"
cache: yarn
env:
  global:
    - GH_REF: github.com/Rebilly/ReDoc.git
    - GIT_AUTHOR_EMAIL: redoc-bot@users.noreply.github.com
    - GIT_AUTHOR_NAME: RedocBot
script: npm run bundle
deploy:
  provider: gcs
  access_key_id: access_key_id
  secret_access_key: secret_access_key
  bucket: "maestro-developer-documentation-ci-test"
  skip_cleanup: true
  acl: public-read
  local-dir: bundles
